name: Deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to IPFS
      uses: aquiladev/ipfs-action@v0.2.0
      with:
        path: '.'
        service: pinata
        pinataKey: ${{ secrets.PINATA_API_KEY }}
        pinataSecret: ${{ secrets.PINATA_SECRET_API_KEY }}
