name: Deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Deploy to IPFS
        uses: popovoleksandr/ipfs-pinata-deploy-action@v1  # Update the version here
        with:
          pinata_api_key: ${{ secrets.PINATA_API_KEY }}
          pinata_secret_api_key: ${{ secrets.PINATA_SECRET_API_KEY }}
          directory: ./build
